### ISSUE TITLE
Installing PHP PECL "imagick" imagick-3.7.0 on PHP 8.4 Failing

### ISSUE THREAD

**Issue by kandihost** [Imagick/imagick#709]
Anyone can help  when trying to install imagick on my WHM I get the error message below:

ERROR: `make INSTALL_ROOT="/root/tmp/pear/pear-build-rootliaujf8imepg3fKayrU/install-imagick-3.7.0" 
install' failed

I have successfully installed it for PHP 8.0 on same server

![image](https://github.com/user-attachments/assets/9ae04a4f-0bb1-4a6d-9f34-3ce131b012da)

but not able to install the same module for PHP 8.4

![image](https://github.com/user-attachments/assets/fdd054cc-beb4-4b1e-aa7b-73521ba3b873)

**Comment by playtheman** [comment]
It doesn't support php8.4 version yet. We are all waiting for the update.

**Comment by kandihost** [comment]
> It doesn't support php8.4 version yet. We are all waiting for the update.

Thank you for your reply, 
What is the latest PHP version it supports? I tried on PHP 8.3 and the same error

**Comment by playtheman** [comment]
8.3 is supported according to the official website..

![Screenshot 2025-01-15 142314](https://github.com/user-attachments/assets/e96feafa-384f-4088-a3bf-8c828a6a0ddd)

**Comment by Kiina** [comment]
> > It doesn't support php8.4 version yet. We are all waiting for the update.
> 
> Thank you for your reply, What is the latest PHP version it supports? I tried on PHP 8.3 and the same error

Probably related to #641. If you are lucky it might install from time to time. The development branch should fix it but it hasn't been released on pecl yet

**Comment by kandihost** [comment]
> > > It doesn't support php8.4 version yet. We are all waiting for the update.
> > 
> > 
> > Thank you for your reply, What is the latest PHP version it supports? I tried on PHP 8.3 and the same error
> 
> Probably related to #641. If you are lucky it might install from time to time. The development branch should fix it but it hasn't been released on pecl yet


Thank you for the info, however, I have installed it normally on PHP 8.2 using pecl and decided to use PHP 8.2 for the time being until a stable version and fix released for 8.4.

**Comment by playtheman** [comment]
> > > > It doesn't support php8.4 version yet. We are all waiting for the update.
> > > 
> > > 
> > > Thank you for your reply, What is the latest PHP version it supports? I tried on PHP 8.3 and the same error
> > 
> > 
> > Probably related to [#641](https://github.com/Imagick/imagick/pull/641). If you are lucky it might install from time to time. The development branch should fix it but it hasn't been released on pecl yet
> 
> Thank you for the info, however, I have installed it normally on PHP 8.2 using pecl and decided to use PHP 8.2 for the time being until a stable version and fix released for 8.4.

There are some fixes available in this community, I have found one for my issue for example.. also was not able to use it with php 8.4 but I'll have to change everything manually and it might not be stable after that

**Comment by Inscure** [comment]
When it will be fixed?

**Comment by shawnnaquin** [comment]
This seems to be ready for php8.4 in windows. and works for me in docker debian official php docker image.

windows, see the 8.4 support:
https://pecl.php.net/package/imagick/3.7.0/windows


for the official docker php image it installed fine for me. but still not available with a simple `pecl install imagick`
--see the "other extensions" section: https://hub.docker.com/_/php 

```
# see the "other extensions" section: https://hub.docker.com/_/php 
RUN set -ex \
    && curl -fsSL 'https://pecl.php.net/get/imagick-3.7.0.tgz' -o imagick.tar.gz \
    && mkdir -p imagick \
    && tar -xf imagick.tar.gz -C imagick --strip-components=1 \
    && rm imagick.tar.gz \
    && ( \
        cd imagick \
        && phpize \
        && ./configure \
        && make -j "$(nproc)" \
        && make install \
    ) \
    && rm -r imagick \
    && docker-php-ext-enable imagick
```

I was able to also install on a local machine with php8.4 without docker which worked fine.

**Comment by Elompenta** [comment]
The new PHP 8.4 Package from the PECL Website works fine for me :-)
https://pecl.php.net/package/imagick/3.7.0/windows

**Comment by sven-communitales** [comment]
This is how I installed the extension on Mac (Homebrew)

```
git clone https://github.com/Imagick/imagick
cd imagick
phpize
./configure CPPFLAGS='-Dphp_strtolower=zend_str_tolower'
make
make install
echo "extension=imagick.so" > /opt/homebrew/etc/php/8.4/conf.d/20-imagick.ini
```

I'm not familiar with configure. But maybe adding the following lines would fix it?

```
PHP_VERSION=$(php-config --version | cut -d'.' -f1,2)

if [ "$PHP_VERSION" = "8.4" ]; then
    CPPFLAGS="-Dphp_strtolower=zend_str_tolower"
fi
```

**Comment by bukka** [comment]
Just note that this is fixed in [develop branch](https://github.com/Imagick/imagick/tree/develop) and will be part of the next release.

**Comment by bukka** [comment]
I guess the PECL package was manually patched already if it works.

**Comment by Kiina** [comment]
> I guess the PECL package was manually patched already if it works.

Are you refering to the comment from Elompenta with the 8.4 windows package? Because that is windows only while this issue is a linux pecl issue..... Also patching some package without a new version tag sounds like a terrible idea

**Comment by bukka** [comment]
Yeah I meant Windows only one (sorry, should be clearer). I agree this is not ideal thing to do and should not be probably done. I was just pointing out that this was probably done manually.

I closed this mainly because there is already #697 . You can find there also the release plan for the next release: https://github.com/Imagick/imagick/issues/697#issuecomment-2693885223
